server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    locations: classpath:/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: bandhub
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/bandhubDB"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/bandhubDB"
    # JPA configuration
  jpa:
    #hibernate:
    #ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        default_schema: bandhub
    open-in-view: false
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
jwt:
  secret: nieh89*Ujj_00098kniu>
  expiration: 60000

#security:
#user:
#password: 1111

logging:
  level:
    org.springframework: ERROR
    by.krutikov: DEBUG
  pattern:
#    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log

#springdoc:
#  api-docs:
#    path: /api-docs