delete from accounts;
delete from user_profiles;
delete from media;
delete from reactions;
delete from experience;
delete from instruments;
delete from reaction_type;
delete from l_account_roles;
delete from roles;
